# Generated by Django 6.0.4 on 2026-05-23 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='expense',
            name='ai_category',
            field=models.CharField(blank=True, help_text='AI-suggested category override', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='category',
            field=models.CharField(choices=[('savings', 'Savings'), ('travel', 'Travel'), ('tech', 'Tech'), ('vehicle', 'Vehicle'), ('education', 'Education'), ('investment', 'Investment'), ('health', 'Health'), ('home', 'Home'), ('other', 'Other')], default='savings', max_length=50),
        ),
        migrations.AddField(
            model_name='goal',
            name='monthly_required',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='on_track',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='predicted_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', 'Food & Dining'), ('shopping', 'Shopping'), ('travel', 'Travel & Transport'), ('bills', 'Bills & Utilities'), ('entertainment', 'Entertainment'), ('health', 'Health & Medical'), ('education', 'Education'), ('investment', 'Investment'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='is_essential',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('overspending', 'Overspending Alert'), ('savings_tip', 'Savings Suggestion'), ('goal_warning', 'Goal Delay Warning'), ('pattern', 'Spending Pattern'), ('general', 'General Insight')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict, help_text='Structured data backing this insight')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CategorizationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('suggested_category', models.CharField(max_length=50)),
                ('confidence', models.FloatField(default=0.0)),
                ('accepted', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='categorization_log', to='core.expense')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default='default', help_text='Groups messages into conversations', max_length=100)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('model_used', models.CharField(default='gemini-1.5-flash', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
