# Generated by Django 6.0.4 on 2026-05-25 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_expense_options_alter_goal_options_and_more'),
        ('core', '0002_profile'),
    ]

    operations = [
    ]
