# Generated by Copilot: Add gmail_address to Profile
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_merge_20260525_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gmail_address',
            field=models.EmailField(blank=True, help_text='The Gmail address connected for auto-sync', max_length=254, null=True),
        ),
    ]
