# Generated by Django 6.0.4 on 2026-05-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_merge_20260525_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='gmail_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='expense',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('gmail', 'Gmail'), ('extension', 'Extension')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='gmail_auto_sync',
            field=models.BooleanField(default=True, help_text='Automatically import expenses from Gmail receipts'),
        ),
    ]
