# Generated by Django 6.0.4 on 2026-05-26 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_expense_gmail_message_id_expense_source_and_more'),
        ('core', '0004_profile_gmail_address'),
    ]

    operations = [
    ]
